export const siteConfig = {
  name: "ARZ Home Remodeling",
  tagline: "Premium Home Remodeling Services",
  description: "Professional bathroom and kitchen remodeling services in Chandler, Arizona. Top-rated home remodeling contractors specializing in luxury renovations.",
  url: "https://arzhomeremodeling.com",
  phone: "(229) 306-5591",
  email: "sales@arzhomeremodeling.com",
  address: {
    street: "6710 W Chicago St",
    city: "Chandler",
    state: "AZ",
    zip: "85226",
    full: "6710 W Chicago St, Chandler, AZ 85226",
    coordinates: {
      lat: 33.33256,
      lng: -111.91689,
    },
  },
  hours: {
    weekdays: "8:00 AM - 6:00 PM",
    saturday: "9:00 AM - 4:00 PM",
    sunday: "Closed",
  },
  social: {
    facebook: "https://facebook.com/arzhomeremodeling",
    instagram: "https://instagram.com/arzhomeremodeling",
    twitter: "https://twitter.com/arzhomeremodeling",
    pinterest: "https://pinterest.com/arzhomeremodeling",
  },
  navigation: [
    { name: "Home", href: "/" },
    { name: "About", href: "/about" },
    { name: "Contact", href: "/contact" },
    { name: "Services", href: "/services" },
    { name: "Blog", href: "/blog" },
  ],
  serviceAreas: [
    "Chandler",
    "Gilbert",
    "Mesa",
    "Tempe",
    "Ahwatukee",
    "Sun Lakes",
  ],
};
